#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: <your application name>
  stack: cedar
  config:
    BUILDPACK_URL: "https://github.com/heroku/heroku-buildpack-multi"
    CONFIG_BY_HEROKU_YML: "heroku_yml"
  addons:
    - scheduler:standard
    - heroku-postgresql:hobby-dev